# Generated by Django 2.2.6 on 2020-02-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('pword', models.CharField(max_length=35)),
                ('tel_no', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_no', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('amount', models.CharField(max_length=35)),
                ('size', models.CharField(max_length=35)),
                ('id_card', models.ImageField(upload_to='')),
                ('title_scan', models.ImageField(upload_to='')),
                ('map_scan', models.ImageField(upload_to='')),
                ('mode_whole', models.BooleanField(default=False)),
                ('mode_part', models.BooleanField(default=False)),
                ('own_full', models.BooleanField(default=False)),
                ('own_lease', models.BooleanField(default=False)),
                ('own_rent', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landbroker.users')),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_no', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('reside', models.CharField(max_length=35)),
                ('size', models.CharField(max_length=35)),
                ('amount', models.CharField(max_length=35)),
                ('size_wanted', models.CharField(max_length=35)),
                ('status', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landbroker.users')),
            ],
        ),
    ]
