# Generated by Django 2.2.6 on 2020-02-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0002_auto_20200203_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='username',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='username',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='uname',
        ),
    ]
