# Generated by Django 2.2.6 on 2020-02-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0003_auto_20200203_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
