# Generated by Django 2.2.6 on 2020-02-17 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landbroker', '0006_auto_20200204_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('tel_no', models.CharField(max_length=35)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='uname',
        ),
        migrations.AddField(
            model_name='buy',
            name='username',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='username',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
