# Generated by Django 2.2.6 on 2020-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0009_auto_20200226_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mob_pswd',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
