# Generated by Django 2.2.6 on 2020-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0010_profile_mob_pswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mob_pswd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
