# Generated by Django 2.2.6 on 2020-03-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0012_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(default='default.png', upload_to='landbroker/'),
        ),
    ]
