# Generated by Django 2.2.6 on 2020-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0013_auto_20200304_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(default='default.png', upload_to='media/landbroker/'),
        ),
    ]
