# Generated by Django 2.2.6 on 2020-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0014_auto_20200305_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='id_card',
            field=models.ImageField(default='default.png', upload_to='landbroker/'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='map_scan',
            field=models.ImageField(default='default.png', upload_to='landbroker/'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='title_scan',
            field=models.ImageField(default='default.png', upload_to='landbroker/'),
        ),
    ]
