# Generated by Django 2.2.6 on 2020-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landbroker', '0015_auto_20200306_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='email',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(default='default.png', upload_to='landbroker/'),
        ),
    ]
